language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DEPENDENCIES=low
    - php: 5.6
      env: DEPENDENCIES=high
    - php: 7.0
      env: DEPENDENCIES=low
    - php: 7.0
      env: DEPENDENCIES=high
    - php: 7.1
      env: DEPENDENCIES=low
    - php: 7.1
      env: DEPENDENCIES=high
    - php: hhvm
      env: DEPENDENCIES=high
  allow_failures:
    - php: hhvm

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer clear-cache

install:
  - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
  - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi

before_script:
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./vendor/bin/phpunit

notifications:
  email: false